#!/bin/bash
# =============================================================================
#  gemini_looker_a2a.sh
#  A2A companion for the Looker analytics agent (Mirador)
#  Author: Jose Maldonado (@joseimj)
# =============================================================================
#
#  WHAT THIS SCRIPT DOES (read this first)
#  ----------------------------------------
#  This script is ADDITIVE to gemini_looker.sh. It takes the exact same agent
#  (my-agents/looker_app/agent.py, generated by the main script) and deploys
#  it a SECOND time as an Agent2Agent (A2A) server on Vertex AI Agent Engine,
#  so that OTHER AGENTS can discover and call it -- not just Gemini Enterprise.
#
#      gemini_looker.sh      -> A2UI path  (humans, inline images in Gemini
#                                           Enterprise)            [untouched]
#      gemini_looker_a2a.sh  -> A2A path   (agents, standard protocol
#                                           endpoints + Agent Card)  [this one]
#
#  Both deployments share the agent code, the service account and the bucket.
#  They are independent: adding A2A never breaks the A2UI experience.
#
#  HOW A2A MAPS ONTO WHAT WE HAVE
#  ------------------------------
#    AgentCard      -> the agent's public identity, served at the well-known
#                      agent-card endpoint. Its "skills" (with examples) are
#                      what an orchestrator reads to decide to delegate a task.
#    AgentExecutor  -> ADK's bridge (A2aAgentExecutor): runs root_agent inside
#                      a Runner and translates A2A tasks <-> ADK events. The
#                      rendered PNGs travel as file parts; text and signed
#                      links as text parts.
#    A2aAgent       -> Agent Engine's wrapper that packages card + executor as
#                      a deployable reasoningEngine (preview, v1beta1).
#
#  THE STEPS THIS SCRIPT RUNS
#  --------------------------
#    -1  Validate configuration       2  Add the A2A dependency to the venv
#     0  Authenticate                 3  Generate deploy_a2a.py (heredoc)
#     1  Preflight: agent app exists  4  Deploy the A2A engine (~15-20 min)
#
#  PREREQUISITE: run gemini_looker.sh first (at least through its STEP 5), so
#  that my-agents/looker_app and the venv already exist. This script fails
#  fast if they don't.
#
#  PREVIEW NOTE: the A2A integration on Agent Engine is in preview (v1beta1)
#  and class/parameter names have moved between SDK releases. Once you have a
#  working combination, PIN versions (marked below) so dev and runtime match.
# =============================================================================

set -euo pipefail

# =============================================================================
# CONFIGURATION  --  use the SAME values as in gemini_looker.sh.
# (Step -1 refuses to run while any value still starts with YOUR_.)
# =============================================================================
PROJECT_ID="YOUR_GOOGLE_CLOUD_PROJECT_ID"
REGION="us-central1"
BUCKET_NAME="YOUR_GCS_BUCKET_NAME"          # same bucket as the main script

# --- Looker connection (API credentials) ---
LOOKER_URL="https://your-instance.looker.com"
LOOKER_CLIENT_ID="YOUR_LOOKER_CLIENT_ID"
LOOKER_CLIENT_SECRET="YOUR_LOOKER_CLIENT_SECRET"
LOOKER_MODELS='["thelook"]'

# --- Reasoning model (same semantics as the main script) ---
AGENT_MODEL_PROVIDER="claude"          # "claude", "claude_native", "anthropic" or "gemini"
CLAUDE_MODEL="claude-sonnet-4-6"
CLAUDE_LOCATION="us-east5"
GEMINI_MODEL="gemini-2.5-flash"

# --- A2A identity ---
A2A_DISPLAY_NAME="gemini-looker-agent-a2a"   # distinct from the A2UI engine
A2A_AGENT_NAME="looker-analytics-agent"
A2A_AGENT_VERSION="1.0.0"
# =============================================================================

# Defensive reset (same convention as the main script).
unset AGENT_SA AGENT_SA_NAME
unset REASONING_ENGINE DEPLOY_LOG DEPLOY_PID DEPLOY_EXIT
unset ELAPSED MINS SECS LAST_LINE

AGENT_SA_NAME="looker-agent-sa"
AGENT_SA="${AGENT_SA_NAME}@${PROJECT_ID}.iam.gserviceaccount.com"

validate_var() {
  local var_name="$1"
  local var_value="$2"
  if [[ -z "$var_value" || "$var_value" == YOUR_* ]]; then
    echo "ERROR: configuration variable '$var_name' is not set."
    exit 1
  fi
}

echo ""
echo "=================================================="
echo " STEP -1: Validate configuration"
echo "=================================================="
validate_var "PROJECT_ID" "$PROJECT_ID"
validate_var "BUCKET_NAME" "$BUCKET_NAME"
validate_var "LOOKER_URL" "$LOOKER_URL"
validate_var "LOOKER_CLIENT_ID" "$LOOKER_CLIENT_ID"
validate_var "LOOKER_CLIENT_SECRET" "$LOOKER_CLIENT_SECRET"
echo "OK: configuration looks complete."

echo ""
echo "=================================================="
echo " STEP 0: Authenticate"
echo "=================================================="
gcloud auth list
gcloud config set project "$PROJECT_ID"

echo ""
echo "=================================================="
echo " STEP 1: Preflight - the agent app and venv must already exist"
echo "=================================================="
# This script does NOT regenerate the agent: the single source of truth for
# agent.py is gemini_looker.sh. We only redeploy what it built.
if [[ ! -f "my-agents/looker_app/agent.py" ]]; then
  echo "ERROR: my-agents/looker_app/agent.py not found."
  echo "Run ./gemini_looker.sh first (at least through its STEP 5)."
  exit 1
fi
if [[ ! -f "my-agents/.venv/bin/activate" ]]; then
  echo "ERROR: my-agents/.venv not found. Run ./gemini_looker.sh first."
  exit 1
fi
# The SA and bucket are created by the main script; verify, don't create.
if ! gcloud iam service-accounts describe "$AGENT_SA" --project="$PROJECT_ID" &>/dev/null; then
  echo "ERROR: service account $AGENT_SA does not exist. Run ./gemini_looker.sh first."
  exit 1
fi
if ! gcloud storage buckets describe "gs://${BUCKET_NAME}" &>/dev/null; then
  echo "ERROR: bucket gs://${BUCKET_NAME} does not exist. Run ./gemini_looker.sh first."
  exit 1
fi
echo "OK: agent app, venv, service account and bucket are in place."

cd my-agents
source .venv/bin/activate

echo ""
echo "=================================================="
echo " STEP 2: Add the A2A dependency to the venv"
echo "=================================================="
pip install --quiet a2a-sdk
pip install --quiet --upgrade "google-cloud-aiplatform[agent_engines,adk]"
# NOTE: the A2A surface is preview. Once it works, pin exact versions here
# AND in the requirements list inside deploy_a2a.py below.
echo "OK: a2a-sdk installed."

echo ""
echo "=================================================="
echo " STEP 3: Generate deploy_a2a.py"
echo "=================================================="
# Written through a single-quoted 'DEPLOYEOF' heredoc so the shell does NOT
# interpolate anything; the file is pure Python and reads the environment.
cat > deploy_a2a.py <<'DEPLOYEOF'
"""deploy_a2a.py -- expose the Looker agent through the A2A protocol.

Generated by gemini_looker_a2a.sh. Creates a SECOND Reasoning Engine that
serves the same root_agent (looker_app/agent.py) through A2A endpoints. The
original AdkApp deployment (A2UI / Gemini Enterprise) is untouched.
"""

import os
import sys

import vertexai
from google.genai import types as genai_types

# A2A protocol types (pip install a2a-sdk)
from a2a.types import AgentCapabilities, AgentCard, AgentSkill

# Agent Engine's A2A wrapper (preview surface)
from vertexai.preview.reasoning_engines import A2aAgent

PROJECT_ID = os.environ["PROJECT_ID"]
REGION = os.environ["REGION"]
STAGING_BUCKET = f"gs://{os.environ['BUCKET_NAME']}"
AGENT_SA = os.environ["AGENT_SA"]
AGENT_NAME = os.environ.get("A2A_AGENT_NAME", "looker-analytics-agent")
DISPLAY_NAME = os.environ.get("A2A_DISPLAY_NAME", "gemini-looker-agent-a2a")
AGENT_VERSION = os.environ.get("A2A_AGENT_VERSION", "1.0.0")

# -----------------------------------------------------------------------------
# 1) AgentCard -- the public identity other agents discover.
#
# One skill per capability (not one generic "Looker" skill): the id, the
# description and especially the examples are what a consuming orchestrator
# matches a user request against. Keep them concrete.
# -----------------------------------------------------------------------------
SKILLS = [
    AgentSkill(
        id="render_dashboard",
        name="Render a Looker dashboard",
        description=(
            "Renders a Looker dashboard as a PNG image, optionally pre-filtered "
            "(e.g. by country or date range). Returns the image plus a signed "
            "interactive Looker link."
        ),
        tags=["looker", "dashboard", "visualization"],
        examples=[
            "show me the sales dashboard",
            "show me dashboard 1 filtered to Brazil, last 30 days",
        ],
    ),
    AgentSkill(
        id="render_chart",
        name="Render a Look or ad-hoc chart",
        description=(
            "Renders a saved Look, or builds an ad-hoc query on a LookML "
            "explore and renders it as a column/bar/line/pie/scatter chart."
        ),
        tags=["looker", "chart", "visualization"],
        examples=["show me look 5", "chart orders by status as a bar chart"],
    ),
    AgentSkill(
        id="query_data",
        name="Answer data questions from Looker",
        description=(
            "Runs live Looker queries through the SDK and answers data "
            "questions with numbers, summaries, or small tables."
        ),
        tags=["looker", "data", "analytics"],
        examples=["how many orders are complete?", "top 5 categories by revenue"],
    ),
    AgentSkill(
        id="signed_links",
        name="Signed interactive Looker links",
        description=(
            "Mints signed SSO embed URLs for dashboards, Looks and explores "
            "(signed server-side by Looker, optionally pre-filtered)."
        ),
        tags=["looker", "embed", "link"],
        examples=["give me the interactive link to dashboard 1"],
    ),
    AgentSkill(
        id="schema_discovery",
        name="Discover the Looker schema",
        description=(
            "Lists the accessible LookML models, their explores, and the "
            "dimensions/measures of an explore, to build valid queries."
        ),
        tags=["looker", "schema", "metadata"],
        examples=["what data is available?", "which fields does order_items have?"],
    ),
]

AGENT_CARD = AgentCard(
    name=AGENT_NAME,
    description=(
        "Looker analytics agent: renders dashboards and charts as images, "
        "answers live data questions via the Looker SDK, and returns signed "
        "interactive Looker links."
    ),
    # Agent Engine serves the card itself; the effective endpoint is derived
    # from the deployed reasoningEngine resource. This placeholder is replaced
    # at serving time -- verify the served card after deploy.
    url="http://localhost:9999/",
    version=AGENT_VERSION,
    default_input_modes=["text/plain"],
    default_output_modes=["text/plain", "image/png"],
    capabilities=AgentCapabilities(streaming=True),
    skills=SKILLS,
)


# -----------------------------------------------------------------------------
# 2) AgentExecutor -- built lazily (a builder) so the heavy imports happen on
# the runtime side, after env vars (LOOKERSDK_*) are in place. We reuse ADK's
# A2aAgentExecutor: it wraps root_agent in a Runner and does the A2A <-> ADK
# translation, including our PNG artifacts as file parts.
# -----------------------------------------------------------------------------
def agent_executor_builder():
    from google.adk.a2a.executor.a2a_agent_executor import A2aAgentExecutor
    from google.adk.artifacts import InMemoryArtifactService
    from google.adk.memory.in_memory_memory_service import InMemoryMemoryService
    from google.adk.runners import Runner
    from google.adk.sessions import InMemorySessionService

    from looker_app.agent import root_agent

    runner = Runner(
        app_name=AGENT_NAME,
        agent=root_agent,
        artifact_service=InMemoryArtifactService(),
        session_service=InMemorySessionService(),
        memory_service=InMemoryMemoryService(),
    )
    return A2aAgentExecutor(runner=runner)


a2a_agent = A2aAgent(
    agent_card=AGENT_CARD,
    agent_executor_builder=agent_executor_builder,
)

# -----------------------------------------------------------------------------
# 3) Deploy. Same env-var injection as deploy.py (credentials are never baked
# into the code), same service account, same staging bucket.
# -----------------------------------------------------------------------------
ENV_VARS = {
    "LOOKERSDK_BASE_URL": os.environ["LOOKER_URL"],
    "LOOKERSDK_CLIENT_ID": os.environ["LOOKER_CLIENT_ID"],
    "LOOKERSDK_CLIENT_SECRET": os.environ["LOOKER_CLIENT_SECRET"],
    "LOOKERSDK_VERIFY_SSL": "true",
    "LOOKER_MODELS": os.environ.get("LOOKER_MODELS", '["thelook"]'),
    "AGENT_MODEL_PROVIDER": os.environ.get("AGENT_MODEL_PROVIDER", "gemini"),
    "CLAUDE_MODEL": os.environ.get("CLAUDE_MODEL", "claude-sonnet-4-6"),
    "GEMINI_MODEL": os.environ.get("GEMINI_MODEL", "gemini-2.5-flash"),
    "VERTEXAI_PROJECT": PROJECT_ID,
    "VERTEXAI_LOCATION": os.environ.get("CLAUDE_LOCATION", REGION),
    "GOOGLE_GENAI_USE_VERTEXAI": "true",
    "GOOGLE_CLOUD_PROJECT": PROJECT_ID,
    "GOOGLE_CLOUD_LOCATION": os.environ.get("CLAUDE_LOCATION", REGION),
}
if os.environ.get("ANTHROPIC_API_KEY"):
    ENV_VARS["ANTHROPIC_API_KEY"] = os.environ["ANTHROPIC_API_KEY"]

REQUIREMENTS = [
    "google-adk",
    "looker_sdk",
    "google-auth",
    "google-cloud-aiplatform[agent_engines,adk]",
    "a2a-sdk",             # A2A protocol types used by the executor bridge
    "requests",
    "litellm",             # AGENT_MODEL_PROVIDER = "claude" / "anthropic"
    "anthropic[vertex]",   # AGENT_MODEL_PROVIDER = "claude_native"
    # PIN exact versions here once the combo works: the A2A surface is
    # preview and moves between releases.
]

client = vertexai.Client(
    project=PROJECT_ID,
    location=REGION,
    http_options=genai_types.HttpOptions(api_version="v1beta1"),  # preview API
)

print(f"Deploying A2A agent as service account: {AGENT_SA}", flush=True)
print(f"Staging bucket: {STAGING_BUCKET}", flush=True)

try:
    remote_app = client.agent_engines.create(
        agent=a2a_agent,
        config={
            "display_name": DISPLAY_NAME,
            "staging_bucket": STAGING_BUCKET,
            "requirements": REQUIREMENTS,
            "extra_packages": ["./looker_app"],
            "env_vars": ENV_VARS,
            "service_account": AGENT_SA,
        },
    )
    # Resource name location differs slightly across SDK releases; try both.
    resource_name = getattr(
        getattr(remote_app, "api_resource", remote_app), "name", None
    ) or getattr(remote_app, "resource_name", "")
    # The shell script parses this exact line to capture the resource name.
    print(f"AGENT_ENGINE_RESOURCE_NAME={resource_name}", flush=True)
except Exception as e:
    print(f"ERROR: {e}", file=sys.stderr, flush=True)
    sys.exit(1)
DEPLOYEOF
echo "deploy_a2a.py generated."

echo ""
echo "=================================================="
echo " STEP 4: Deploy the A2A agent to Vertex AI Agent Engine"
echo "  (takes ~15-20 min; runs as: $AGENT_SA)"
echo "=================================================="

# Export what deploy_a2a.py reads from the environment.
export PROJECT_ID REGION BUCKET_NAME AGENT_SA
export LOOKER_URL LOOKER_CLIENT_ID LOOKER_CLIENT_SECRET LOOKER_MODELS
export AGENT_MODEL_PROVIDER CLAUDE_MODEL CLAUDE_LOCATION GEMINI_MODEL
export A2A_DISPLAY_NAME A2A_AGENT_NAME A2A_AGENT_VERSION

# Same heartbeat pattern as the main script: long deploys run in the background
# and print the latest log line every 15s so interactive terminals (e.g. Cloud
# Shell) never look frozen or time out on inactivity.
DEPLOY_LOG="/tmp/a2a_deploy_$$.log"
> "$DEPLOY_LOG"

python deploy_a2a.py > "$DEPLOY_LOG" 2>&1 &
DEPLOY_PID=$!
echo "Deploy running in background (PID: $DEPLOY_PID)"

ELAPSED=0
while kill -0 $DEPLOY_PID 2>/dev/null; do
  sleep 15
  ELAPSED=$((ELAPSED + 15))
  MINS=$((ELAPSED / 60))
  SECS=$((ELAPSED % 60))
  LAST_LINE=$(tail -1 "$DEPLOY_LOG" 2>/dev/null || echo "...")
  echo "[${MINS}m${SECS}s] $LAST_LINE"
done

wait $DEPLOY_PID
DEPLOY_EXIT=$?

echo ""
echo "=== DEPLOY OUTPUT ==="
cat "$DEPLOY_LOG"
echo "====================="

if [ $DEPLOY_EXIT -ne 0 ]; then
  echo "ERROR: A2A deploy failed (see output above; for runtime errors check"
  echo "       Logs Explorer -> resource type 'Vertex AI Reasoning Engine')."
  echo "NOTE: the A2A surface is preview; if an import or parameter name fails,"
  echo "      check the installed versions of google-cloud-aiplatform / a2a-sdk"
  echo "      against the current 'Get started with A2A on Agent Engine' notebook,"
  echo "      then pin matching versions in STEP 2 and in deploy_a2a.py."
  exit 1
fi

# Capture the Reasoning Engine resource name (two fallbacks, in order),
# filtering by THIS deploy's display name so we never grab the A2UI engine.
REASONING_ENGINE=$(grep "AGENT_ENGINE_RESOURCE_NAME=" "$DEPLOY_LOG" | tail -1 | cut -d= -f2- || true)

if [ -z "$REASONING_ENGINE" ]; then
  cat > /tmp/extract_a2a_engine.py <<'PYPARSER'
import json, os, sys
try:
    d = json.load(sys.stdin)
    target = os.environ.get("A2A_DISPLAY_NAME", "gemini-looker-agent-a2a")
    engines = [e for e in d.get('reasoningEngines', []) if e.get('displayName') == target]
    if engines:
        print(engines[-1]['name'])
except Exception:
    pass
PYPARSER
  REASONING_ENGINE=$(curl -s -H "Authorization: Bearer $(gcloud auth print-access-token)" \
    "https://${REGION}-aiplatform.googleapis.com/v1beta1/projects/${PROJECT_ID}/locations/${REGION}/reasoningEngines" \
    | python3 /tmp/extract_a2a_engine.py)
fi

if [ -z "$REASONING_ENGINE" ]; then
  echo "ERROR: could not determine the A2A Reasoning Engine resource name."
  exit 1
fi

cd ..

echo ""
echo "=================================================="
echo " A2A SETUP COMPLETE"
echo "=================================================="
echo ""
echo "  A2A Reasoning Engine : $REASONING_ENGINE"
echo "  Agent SA             : $AGENT_SA"
echo "  Staging/Artifacts    : gs://${BUCKET_NAME}"
echo ""
echo "The agent now has two front doors:"
echo "  A2UI -> Gemini Enterprise (the engine deployed by gemini_looker.sh)"
echo "  A2A  -> this engine, for other agents (standard protocol endpoints)"
echo ""
echo "Next steps:"
echo "  1. Verify the served Agent Card (skills, capabilities) from Python:"
echo "       client = vertexai.Client(project=..., location=...,"
echo "                http_options=HttpOptions(api_version='v1beta1'))"
echo "       remote = client.agent_engines.get(name='$REASONING_ENGINE')"
echo "  2. Grant consumers access: each consuming agent's service account"
echo "     needs roles/aiplatform.user on project ${PROJECT_ID}."
echo "  3. From an ADK consumer, point a RemoteA2aAgent at the agent card URL."
echo ""
echo "Reminder: image artifacts render natively in Gemini Enterprise (A2UI);"
echo "generic A2A clients receive the PNG as a file part, and always get the"
echo "signed Looker link as a text fallback."
